a = int(input("enter num1"))
b = int(input("enter num2"))
print("Addition of {} and {} is {}".format(a,b,a+b))
print("Subtraction of {} and {} is {}".format(a,b,a-b))
print("Multiplication of {} and {} is {}".format(a,b,a*b))
print("Floor division of {} and {} is {}".format(a,b,a//b))                                                   
print("Decimal division of {} and {} is {}".format(a,b,a/b))
print("Remainder of {} divided by {} is {}".format(a,b,a%b))
print("{} power {} is {}.".format(a,b,a**b))
